#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

cd "$(dirname "$0")/.."

echo "==> Running ruff"
uv run ruff format
uv run ruff check --fix .
# run formatting again to fix any inconsistencies when imports are stripped
uv run ruff format

echo "==> Formatting docs"
api_docs=()
while IFS= read -r -d '' api_doc; do
  api_docs+=("$api_doc")
done < <(find . -type f -name api.md -print0)
uv run python scripts/utils/ruffen-docs.py README.md "${api_docs[@]}"
