#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2026 Xquik contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

cd "$(dirname "$0")/.."
export DEFER_PYDANTIC_BUILD=false

# Pin patch floors to exclude prereleases.
PY_VERSION_MIN=">=3.10.0"
PY_VERSION_MAX=">=3.14.0"

function run_tests() {
    echo "==> Running tests with Pydantic v2"
    uv run --isolated --all-extras pytest "$@"

    # Pydantic v1 does not support the latest Python.
    if [[ "$UV_PYTHON" != "$PY_VERSION_MAX" ]]; then
        echo "==> Running tests with Pydantic v1"
        uv run --isolated --all-extras --group=pydantic-v1 pytest "$@"
    fi
}

# Run one Python version when UV_PYTHON is set.
if [[ -n "$UV_PYTHON" ]]; then
  run_tests "$@"
else
  # Otherwise, test minimum and maximum versions.
  echo "==> Running tests for Python $PY_VERSION_MIN"
  UV_PYTHON="$PY_VERSION_MIN" run_tests "$@"

  echo "==> Running tests for Python $PY_VERSION_MAX"
  UV_PYTHON="$PY_VERSION_MAX" run_tests "$@"
fi
